### ISSUE TITLE
Improvement idea for sampling method

### ISSUE THREAD

**Issue by vladhondru25** [muresanuliviu/RTG#1]
Hello and thank you very much for your work.

I wanted to make a suggestion. Currently, if there are only 2 players in the first urnes, the aglorithm should compensate with more players from the second urne. My idea was: 
- assign a weight to all players depending on their urne
- when sampling, you have to make sure each team has the same (or at least very similar) cumulated weight

**Comment by muresanuliviu** [comment]
Hello, Vlad, thank you very much for your comment and interest in this project! I will try to implement what you're suggesting. Feel free to contribute or highlight any other suggestions you have! 🥹😇
